name: Release Desktop Apps

on:
  push:
    tags:
      - 'v*.*.*'        # 正式版本: v1.0.0, v2.1.3
      - 'v*.*.*-*'      # 预览版本: v1.0.0-beta.1, v1.0.0-rc.1

env:
  NODE_VERSION: '22'
  PNPM_VERSION: '10.6.1'

jobs:
  # 构建 Windows 版本
  build-windows:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: 安装依赖
        run: pnpm install

      - name: 构建 Desktop 应用
        run: pnpm build:desktop

      - name: 验证构建产物
        shell: bash
        run: |
          echo "Checking build artifacts..."
          ls -la packages/desktop/dist/ || echo "No dist directory found"
          
          # 检查是否有构建产物
          exe_files=$(find packages/desktop/dist -name "*.exe" 2>/dev/null | wc -l)
          zip_files=$(find packages/desktop/dist -name "*.zip" 2>/dev/null | wc -l)
          
          echo "Found $exe_files .exe files and $zip_files .zip files"
          
          if [ "$exe_files" -eq 0 ] && [ "$zip_files" -eq 0 ]; then
            echo "Error: No build artifacts (.exe or .zip) found in packages/desktop/dist/"
            echo "Directory contents:"
            find packages/desktop/dist -type f 2>/dev/null || echo "Directory not found or empty"
            exit 1
          fi
          
          echo "Build artifacts verification passed"

      - name: 上传 Windows 构建产物
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            packages/desktop/dist/PromptOptimizer-*.exe
            packages/desktop/dist/PromptOptimizer-*.zip
            packages/desktop/dist/latest*.yml
          retention-days: 30

  # 构建 macOS 版本
  build-macos:
    runs-on: macos-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: 安装依赖
        run: pnpm install

      - name: 构建 Desktop 应用
        run: pnpm build:desktop

      - name: 验证构建产物
        run: |
          echo "Checking build artifacts..."
          ls -la packages/desktop/dist/ || echo "No dist directory found"
          
          # 检查是否有构建产物
          dmg_files=$(find packages/desktop/dist -name "*.dmg" 2>/dev/null | wc -l)
          zip_files=$(find packages/desktop/dist -name "*.zip" 2>/dev/null | wc -l)
          
          echo "Found $dmg_files .dmg files and $zip_files .zip files"
          
          if [ "$dmg_files" -eq 0 ] && [ "$zip_files" -eq 0 ]; then
            echo "Error: No build artifacts (.dmg or .zip) found in packages/desktop/dist/"
            echo "Directory contents:"
            find packages/desktop/dist -type f 2>/dev/null || echo "Directory not found or empty"
            exit 1
          fi
          
          echo "Build artifacts verification passed"

      - name: 上传 macOS 构建产物
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            packages/desktop/dist/*.dmg
            packages/desktop/dist/*.zip
            packages/desktop/dist/*.yml
          retention-days: 30

  # 构建 Linux 版本
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: 安装依赖
        run: pnpm install

      - name: 构建 Desktop 应用
        run: pnpm build:desktop

      - name: 验证构建产物
        run: |
          echo "Checking build artifacts..."
          ls -la packages/desktop/dist/ || echo "No dist directory found"
          
          # 检查是否有构建产物
          appimage_files=$(find packages/desktop/dist -name "*.AppImage" 2>/dev/null | wc -l)
          zip_files=$(find packages/desktop/dist -name "*.zip" 2>/dev/null | wc -l)
          
          echo "Found $appimage_files .AppImage files and $zip_files .zip files"
          
          if [ "$appimage_files" -eq 0 ] && [ "$zip_files" -eq 0 ]; then
            echo "Error: No build artifacts (.AppImage or .zip) found in packages/desktop/dist/"
            echo "Directory contents:"
            find packages/desktop/dist -type f 2>/dev/null || echo "Directory not found or empty"
            exit 1
          fi
          
          echo "Build artifacts verification passed"

      - name: 上传 Linux 构建产物
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            packages/desktop/dist/*.AppImage
            packages/desktop/dist/*.zip
            packages/desktop/dist/*.yml
          retention-days: 30

  # 创建 GitHub Release
  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 获取版本号和类型
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

          # 判断是否为预览版本
          if [[ $VERSION == *"-"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
            echo "This is a prerelease version"
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
            echo "This is a stable release"
          fi

      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: 显示构建产物
        run: |
          echo "构建产物列表:"
          find ./artifacts -type f -name "*" | sort

      - name: 移除调试文件
        run: |
          echo "Removing debug files..."
          find ./artifacts -type f -name "builder-debug.yml" -delete
          echo "Final artifact list after cleaning:"
          find ./artifacts -type f | sort

      - name: 生成 Release Notes
        id: release_notes
        run: |
          # 获取上一个tag
          PREVIOUS_TAG=$(git tag --sort=-version:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -2 | tail -1)
          CURRENT_TAG=${{ steps.version.outputs.version }}

          echo "Previous tag: $PREVIOUS_TAG"
          echo "Current tag: $CURRENT_TAG"

          # 生成commit历史（处理多行和长commit）
          if [ -n "$PREVIOUS_TAG" ]; then
            COMMITS=$(git log --pretty=format:"%s|%h" $PREVIOUS_TAG..$CURRENT_TAG | while IFS='|' read -r subject hash; do
              # 截断过长的commit message（保留前80个字符）
              if [ ${#subject} -gt 80 ]; then
                subject="${subject:0:77}..."
              fi
              echo "- $subject (\`$hash\`)"
            done)
          else
            COMMITS=$(git log --pretty=format:"%s|%h" $CURRENT_TAG | while IFS='|' read -r subject hash; do
              # 截断过长的commit message（保留前80个字符）
              if [ ${#subject} -gt 80 ]; then
                subject="${subject:0:77}..."
              fi
              echo "- $subject (\`$hash\`)"
            done)
          fi

          # 检查是否有commits
          if [ -z "$COMMITS" ]; then
            COMMITS="- 首次发布"
          fi

          # 限制commits数量（最多显示20个）
          COMMITS_LIMITED=$(echo "$COMMITS" | head -20)
          COMMITS_COUNT=$(echo "$COMMITS" | wc -l)

          if [ $COMMITS_COUNT -gt 20 ]; then
            COMMITS_LIMITED="$COMMITS_LIMITED

          ... 以及其他 $((COMMITS_COUNT - 20)) 个提交"
          fi

          # 创建release notes
          cat > release_notes.md << EOF
          ## 🚀 Prompt Optimizer $CURRENT_TAG

          ### 📦 下载
          - **Windows**: \`PromptOptimizer-*-win-x64.exe\` (安装程序) 或 \`PromptOptimizer-*-win-x64.zip\` (便携版)
          - **macOS**: \`PromptOptimizer-*-darwin-x64.dmg\` (安装程序) 或 \`PromptOptimizer-*-darwin-x64.zip\` (便携版)
          - **Linux**: \`PromptOptimizer-*-linux-x86_64.AppImage\` (便携版) 或 \`PromptOptimizer-*-linux-x64.zip\` (便携版)

          ### 🔧 安装说明
          - **Windows**: 
            - **安装程序**: 下载 \`.exe\` 文件，双击运行安装向导
            - **便携版**: 下载 \`.zip\` 文件，解压后运行 \`PromptOptimizer.exe\`
          - **macOS**: 
            - **安装程序**: 下载 \`.dmg\` 文件，双击挂载后拖拽到应用程序文件夹
            - **便携版**: 下载 \`.zip\` 文件，解压后运行 \`PromptOptimizer.app\`
          - **Linux**: 
            - **AppImage**: 下载 \`.AppImage\` 文件，添加执行权限后直接运行
            - **便携版**: 下载 \`.zip\` 文件，解压后运行 \`PromptOptimizer\`

          ### 📝 更新内容
          $COMMITS_LIMITED

          ### 🔗 更多信息
          - **项目主页**: [GitHub Repository](https://github.com/${{ github.repository }})
          - **问题反馈**: [Issues](https://github.com/${{ github.repository }}/issues)
          - **讨论交流**: [Discussions](https://github.com/${{ github.repository }}/discussions)

          ---
          **提示**: 如果需要查看完整的提交历史，请访问 [GitHub Commits](https://github.com/\${{ github.repository }}/compare/$PREVIOUS_TAG...$CURRENT_TAG)
          EOF

          echo "Generated release notes:"
          cat release_notes.md

      - name: 创建 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.is_prerelease == 'true' && format('Preview {0}', steps.version.outputs.version) || format('Release {0}', steps.version.outputs.version) }}
          body_path: release_notes.md
          files: |
            ./artifacts/windows-build/*
            ./artifacts/macos-build/*
            ./artifacts/linux-build/*
          draft: false
          prerelease: ${{ steps.version.outputs.is_prerelease == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
